### ISSUE TITLE
差分包疑问

### ISSUE THREAD

**Issue by keyescgm** [wanliyang1990/BsDiffYwl5320#2]
1、当new.apk大小 小于 old.apk大小的时候能打出差分包吗？而且差分包可用吗？ 
2、当new.apk 与 old.apk 大小相差很近，但是打出的差分包却还是很大，怎么解决？
3、如何分渠道打差分包？
4、如何判断签名一致，而不是移花接木？
5、还没想出来

**Comment by wanliyang1990** [comment]
1、可以打出来，也可以用，这种你实际验证一下自然就清楚了。
2、如果apk本身大小很小，就没必要用增量更新了，体现不出优势；对于apk大小比较大的才能体现出优势，你也可以实际测试。
3、分渠道打包就需要传递渠道号，然后后台根据渠道号来生成相应的增量包。
4、不需要判断签名，判断文件MD5就行，何来移花接木？？？
5、以上这些问题，都是可以实际验证和解决的，要多动手尝试！！！

**Comment by blackblock1523** [comment]
> 3、分渠道打包就需要传递渠道号，然后后台根据渠道号来生成相应的增量包。
生成增量包的时间可能会大于下载增量包的时间，这段时间怎么控制？
